export const USER_LOGIN_REQUEST = 'USER_LOGIN_REQUEST';
export const USER_LOGIN_SUCCESS = 'USER_LOGIN_SUCCESS';
export const USER_LOGIN_FAIL = 'USER_LOGIN_FAIL';

export const USER_LOGOUT = 'USER_LOGOUT';

export const USER_REGISTER_REQUEST = 'USER_REGISTER_REQUEST';
export const USER_REGISTER_SUCCESS = 'USER_REGISTER_SUCCESS';
export const USER_REGISTER_FAIL = 'USER_REGISTER_FAIL';

export const CREATE_ADDRESS_REQUEST = 'CREATE_ADDRESS_REQUEST';
export const CREATE_ADDRESS_SUCCESS = 'CREATE_ADDRESS_SUCCESS';
export const CREATE_ADDRESS_FAIL = 'CREATE_ADDRESS_FAIL';
export const CREATE_ADDRESS_RESET = 'CREATE_ADDRESS_RESET';

export const UPDATE_ADDRESS_REQUEST = 'UPDATE_ADDRESS_REQUEST';
export const UPDATE_ADDRESS_SUCCESS = 'UPDATE_ADDRESS_SUCCESS';
export const UPDATE_ADDRESS_FAIL = 'UPDATE_ADDRESS_FAIL';
export const UPDATE_ADDRESS_RESET = 'UPDATE_ADDRESS_RESET';

export const ADDRESS_DETAILS_REQUEST = 'ADDRESS_DETAILS_REQUEST';
export const ADDRESS_DETAILS_SUCCESS = 'ADDRESS_DETAILS_SUCCESS';
export const ADDRESS_DETAILS_FAIL = 'ADDRESS_DETAILS_FAIL';
export const ADDRESS_DETAILS_RESET = 'ADDRESS_DETAILS_RESET';

export const DELETE_ADDRESS_REQUEST = 'DELETE_ADDRESS_REQUEST';
export const DELETE_ADDRESS_SUCCESS = 'DELETE_ADDRESS_SUCCESS';
export const DELETE_ADDRESS_FAIL = 'DELETE_ADDRESS_FAIL';
export const DELETE_ADDRESS_RESET = 'DELETE_ADDRESS_RESET';

export const APPLY_COUPON_REQUEST = 'APPLY_COUPON_REQUEST';
export const APPLY_COUPON_SUCCESS = 'APPLY_COUPON_SUCCESS';
export const APPLY_COUPON_FAIL = 'APPLY_COUPON_FAIL';
export const APPLY_COUPON_RESET = 'APPLY_COUPON_RESET';

export const REMOVE_COUPON_REQUEST = 'REMOVE_COUPON_REQUEST';
export const REMOVE_COUPON_SUCCESS = 'REMOVE_COUPON_SUCCESS';
export const REMOVE_COUPON_FAIL = 'REMOVE_COUPON_FAIL';
export const REMOVE_COUPON_RESET = 'REMOVE_COUPON_RESET';

export const ADD_PRODUCT_TO_WISHLIST_REQUEST = 'ADD_PRODUCT_TO_WISHLIST_REQUEST';
export const ADD_PRODUCT_TO_WISHLIST_SUCCESS = 'ADD_PRODUCT_TO_WISHLIST_SUCCESS';
export const ADD_PRODUCT_TO_WISHLIST_FAIL = 'ADD_PRODUCT_TO_WISHLIST_FAIL';
export const ADD_PRODUCT_TO_WISHLIST_RESET = 'ADD_PRODUCT_TO_WISHLIST_RESET';

export const GET_WISHLIST_REQUEST = 'GET_WISHLIST_REQUEST';
export const GET_WISHLIST_SUCCESS = 'GET_WISHLIST_SUCCESS';
export const GET_WISHLIST_FAIL = 'GET_WISHLIST_FAIL';
export const GET_WISHLIST_RESET = 'GET_WISHLIST_RESET';

export const REMOVE_PRODUCT_FROM_WISHLIST_REQUEST = 'REMOVE_PRODUCT_FROM_WISHLIST_REQUEST';
export const REMOVE_PRODUCT_FROM_WISHLIST_SUCCESS = 'REMOVE_PRODUCT_FROM_WISHLIST_SUCCESS';
export const REMOVE_PRODUCT_FROM_WISHLIST_FAIL = 'REMOVE_PRODUCT_FROM_WISHLIST_FAIL';
export const REMOVE_PRODUCT_FROM_WISHLIST_RESET = 'REMOVE_PRODUCT_FROM_WISHLIST_RESET';
